-- DropForeignKey
ALTER TABLE "Inventario" DROP CONSTRAINT "Inventario_ISBN_fkey";

-- DropForeignKey
ALTER TABLE "Inventario" DROP CONSTRAINT "Inventario_ISSN_fkey";

-- AlterTable
ALTER TABLE "Inventario" ALTER COLUMN "ISBN" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "ISSN" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "Seccion_Biblioteca" SET DATA TYPE VARCHAR(30);

-- AddForeignKey
ALTER TABLE "Inventario" ADD CONSTRAINT "Inventario_ISSN_fkey" FOREIGN KEY ("ISSN") REFERENCES "Revista"("ISSN") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Inventario" ADD CONSTRAINT "Inventario_ISBN_fkey" FOREIGN KEY ("ISBN") REFERENCES "Libro"("ISBN") ON DELETE SET NULL ON UPDATE CASCADE;
